######################################################################
##
## Filename: test_show_7segment.udo
## Created on: Fri Oct 30 11:08:19 PM Iran Standard Time 2020
##
## Auto generated by Project Navigator for Post-Route Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
